//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotDontLie.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BotResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BotDontLie.Common.Properties.BotResource", typeof(BotResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search for a game in NBA any season from 1979 onwards....
        /// </summary>
        public static string FindGamesText {
            get {
                return ResourceManager.GetString("FindGamesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Games.
        /// </summary>
        public static string FindGamesTitleText {
            get {
                return ResourceManager.GetString("FindGamesTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search for an NBA player by their last name....
        /// </summary>
        public static string FindPlayersText {
            get {
                return ResourceManager.GetString("FindPlayersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Players.
        /// </summary>
        public static string FindPlayersTitleText {
            get {
                return ResourceManager.GetString("FindPlayersTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can search for an NBA franchise.....
        /// </summary>
        public static string FindTeamsText {
            get {
                return ResourceManager.GetString("FindTeamsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Teams.
        /// </summary>
        public static string FindTeamsTitleText {
            get {
                return ResourceManager.GetString("FindTeamsTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string PlayerFullNameFormat {
            get {
                return ResourceManager.GetString("PlayerFullNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        public static string TakeATourCTATitle {
            get {
                return ResourceManager.GetString("TakeATourCTATitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NBA Franchise.
        /// </summary>
        public static string TeamResponseTitleText {
            get {
                return ResourceManager.GetString("TeamResponseTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
